[Refeactor] 리뷰 기능 리팩터링
PatientPaI/backend pull request #185
Opened 2024-07-31 06:31 UTC by namomi

## ✨ 작업 내용
-  Member는 본인이 포함된 Review를 확인 할 수 있게 String 타입에서 Member타입으로 변경
- 테스트 객체 생성 코드를 ~ Fixture 클래스로 만들어서 통과
- 수락된 매칭 중에서 careEndDateTime 이 날짜로 리뷰 시작을 적용했습니다.

2024-07-31 06:36 UTC, namomi commented on src/main/java/com/patientpal/backend/security/jwt/JwtTokenProvider.java
> +        redisTemplate.opsForValue().set(token, "invalid", 1, TimeUnit.MILLISECONDS);
레디스 블랙리스트  만들어서 할 예정

2024-08-01 03:31 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/domain/Review.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
테이블명 소문자 + 복수형인 reviews로 맞추는게 좋을 것 같습니다!

2024-08-01 03:33 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/domain/Review.java
> +    @ManyToOne
@ManyToOne의 기본 전략이 Fetch.EAGER여서 프록시 즉시 로딩으로 인한 성능 저하 이슈 발생 예방 차원에서
LAZY로 지정하는게 좋을 것 같습니다.

2024-08-01 03:34 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/domain/Review.java
> +    private Member reviewer;
Member 와 Review를 양방향이 아닌 단방향으로 설정하신 이유가 있으실까요?

2024-08-01 03:37 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/dto/ReviewRequest.java
>  @NoArgsConstructor
다른 패키지에서 기본생성자를 통한 객체 생성을 막기 위해
@NoArgsConstructor(access = AccessLevel.PRIVATE)로 접근제어자를 설정하면 좋을 것 같습니다.

2024-08-01 03:45 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/service/ReviewService.java
ReviewController 매개변수에 jwt토큰 인증을 넣으셔야 할 것 같습니다. 
이후 DTO가 아닌 토큰을 통해 reviewer를 찾으면 될 것 같아요.

2024-08-01 03:47 UTC, LeeHusung commented on src/test/java/com/patientpal/backend/review/controller/ReviewControllerTest.java
> +
package com.patientpal.backend.fixtures.member 패키지에 MemberFixture가 이미 존재하는데 따로 review 패키지에 Fixture를 또 만드신 이유가 있으실까요?

2024-08-01 03:49 UTC, LeeHusung commented on src/test/java/com/patientpal/backend/review/controller/ReviewControllerTest.java
> +            ReviewResponse reviewResponse = new ReviewResponse(1L, 1L, "John Doe", 2L, "Caregiver A", 5, "Excellent service");
dto 관련 생성 코드도 특이 사항이 아니라면 생성자에 값 직접 하드코딩하는 것이 아니라 fixture에 만들어서 중복 사용되도록 하면 될 것 같습니다.

2024-08-01 03:51 UTC, namomi commented on src/main/java/com/patientpal/backend/review/domain/Review.java
>      @GeneratedValue(strategy = GenerationType.IDENTITY)
네, 그렇게 하겠습니다.

2024-08-01 03:51 UTC, namomi commented on src/main/java/com/patientpal/backend/review/domain/Review.java
> +    @ManyToOne
네, 알겠습니다.

2024-08-01 03:53 UTC, LeeHusung commented on src/test/java/com/patientpal/backend/review/service/ReviewServiceTest.java
> +        match = createMatch();
마찬가지로 review패키지에 fixture를 따로 만드신 이유가 있으신지 궁금합니다

2024-08-01 03:53 UTC, namomi commented on src/main/java/com/patientpal/backend/review/domain/Review.java
> +    private Member reviewer;
일단 복잡도 줄일려고 단방향으로 했는데 양방향으로 할까요? 
회원이 리뷰 참조 할려하면 양방향으로 해야겠네요

2024-08-01 03:54 UTC, namomi commented on src/main/java/com/patientpal/backend/review/dto/ReviewRequest.java
>  @NoArgsConstructor
네, 알겠습니다.

2024-08-01 03:55 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
> +    Optional<Match> findCompleteMatchForCaregiver(@Param("caregiverId") Long caregiverId);
환자에 대한 메서드는 일부로 안넣으신걸까요?

2024-08-01 04:16 UTC, namomi commented on src/test/java/com/patientpal/backend/review/controller/ReviewControllerTest.java
> +
이미 존재하는거였군요 
수정 하겠습니다.

2024-08-01 04:16 UTC, namomi commented on src/main/java/com/patientpal/backend/review/service/ReviewService.java
네, 알겠습니댜.

2024-08-01 04:43 UTC, namomi commented on src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
> +    Optional<Match> findCompleteMatchForCaregiver(@Param("caregiverId") Long caregiverId);
해당 메서드는 간호인을 기준으로 완료된 매칭을 찾기 위해 설계했습니다. 환자에 대한 매칭을 찾는 메서드도 구현할 수 있으며, 이 경우 간호인 정보는 필요하지 않습니다.

2024-08-01 04:45 UTC, namomi commented on src/test/java/com/patientpal/backend/review/controller/ReviewControllerTest.java
> +            ReviewResponse reviewResponse = new ReviewResponse(1L, 1L, "John Doe", 2L, "Caregiver A", 5, "Excellent service");
네, 알겠습니다.

2024-08-01 04:46 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
> +    Optional<Match> findCompleteMatchForCaregiver(@Param("caregiverId") Long caregiverId);
네 알겠습니다. caregiverId가 아닌 memberId로 바꿔서 간병인과 환자 모두에게 사용할 수 있어도 괜찮을 것 같습니다

2024-08-01 04:46 UTC, namomi commented on src/test/java/com/patientpal/backend/review/service/ReviewServiceTest.java
> +        match = createMatch();
fixture 관리하기 위해서 만든건데 혹시 따른데 보관하는데가 있을까요?

2024-08-01 04:52 UTC, LeeHusung commented on src/test/java/com/patientpal/backend/review/service/ReviewServiceTest.java
> +        match = createMatch();
createCaregiver, createMatch 와 같은 메서드들은 기존 package com.patientpal.backend.fixtures.*;
패키지에 존재합니다. review/패키지에 새로 만드는 것보다 기존 패키지에서 사용하거나 추가하는 게 통일성 측면에서 좋을 것 같습니다.

2024-08-01 04:54 UTC, namomi commented on src/test/java/com/patientpal/backend/review/service/ReviewServiceTest.java
> +        match = createMatch();
네, 알겠습니다.

2024-08-05 11:33 UTC, LeeHusung requested changes
1. 테이블 명 수정
2. Fetch 전략 수정 (EAGER -> LAZY)
3. 연관관계 변경 (단방향 -> 양방향)
4. ReviewController에 JWT 토큰 인증 절차 추가
5. 테스트 Fixture 클래스 패키지 위치 수정
위와 같이 먼저 수정되어야 될 것 같습니다!
* 올린 PR을 수정할 수 있는 amend라는 git 명령어도 존재합니다

2024-08-06 04:58 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/controller/ReviewController.java
> +                                                       @AuthenticationPrincipal UserDetails userDetails) {
리뷰 수정/ 리뷰 삭제 api도 jwt토큰으로 인증이 필요할 듯 합니다. 혹시 안붙이신 이유가 있을까요?

2024-08-06 04:59 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/domain/Review.java
>  @Entity
테이블 명 수정이 안된거 같은데 맞나요?

2024-08-06 05:45 UTC, namomi commented on src/main/java/com/patientpal/backend/review/domain/Review.java
>  @Entity
확인해서 리네임 해서 다시 올렸습니다

2024-08-06 05:52 UTC, namomi commented on src/main/java/com/patientpal/backend/review/controller/ReviewController.java
> +                                                       @AuthenticationPrincipal UserDetails userDetails) {
앞단에서 수정/ 삭제 버튼을 해당회원 유저만 보이게 할 수 있어서 안해도 될까 생각했는데 추가하겠습니다

2024-08-06 05:56 UTC, LeeHusung commented on src/main/java/com/patientpal/backend/review/controller/ReviewController.java
> +                                                       @AuthenticationPrincipal UserDetails userDetails) {
넵 postman같은 api 클라이언트를 통해 사용자가 악의로 다른 리뷰 수정/삭제 작업을 진행할 수 있기에 보안을 위해서 토큰 추가, 본인이 작성한 리뷰인지 확인하는 코드를 추가하는게 좋을 것 같습니다.

2024-08-06 08:20 UTC, LeeHusung approved these changes
고생하셨습니다 ! 머지하겠습니다

2024-08-06 08:24 UTC, merged